name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install && npm install --save-dev electron-builder


      - name: Build executable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist
      - name: Check directory after build
        run: ls -R
      - name: Author
        run: git config --global user.email "vladiusha13@outlook.com" && git config --global user.name "murfi547"
      - name: Add dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git add dist/ && git commit -m "Добавлена папка dist" && git push origin main



